---
spring.application.name: s1rates

management:
  endpoints:
    web:
      exposure:
        include:
          - "health"
          - "info"
          - "mappings"
          - "env"
          - "refresh"